### PR TITLE
Breaking

### PR DESCRIPTION
**Pull request by notlee**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-quote bundle size difference from 2.2.24 to 54fddece4d341bba3108427d9600ebe4e3478152
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-quote bundle size difference from 2.2.24 to dfa7a913f6caf7e9d478b845c0b3e6cd773e61a4
css: 0.75kb increase (0.07kb/gzip)

**Comment by origamiserviceuser** [comment]
o-quote bundle size difference from 2.2.24 to ca68f546fa6944b15f5b65c6642e254f7617b1df
css, master: 0.75kb increase (0.07kb/gzip)

**Comment by notlee** [comment]
@chee shall we make the base mixins be private and included in the standard mixin by default? Context: https://github.com/Financial-Times/o-layout/pull/111#discussion_r348075233

**Comment by notlee** [comment]
👍

**Pull request merged**
